#!/bin/bash
#
osch=0
echo "1. Unix"
echo "2. Linux"
echo -n "Select your os choice [1 or 2]? "
read vastus
if [ $vastus -eq 1 ] ; then
     echo "You Pick Unix"
else
       if [ $vastus -eq 2 ] ; then
             echo "You Pick Linux"
       else
             echo "Why don't you like Unix/Linux OS."
       fi
fi


